/**
 * The DeleteFlightWindow class represents a window for deleting a flight from the flight booking system.
 * It provides a user interface with text fields for entering the flight ID and buttons for deleting or canceling the operation.
 * Upon confirmation, the specified flight will be deleted from the system.
 * This class implements the ActionListener interface to handle button clicks.
 */

package bcu.cmp5332.bookingsystem.gui;

import bcu.cmp5332.bookingsystem.commands.Command;
import bcu.cmp5332.bookingsystem.commands.DeleteFlight;
import bcu.cmp5332.bookingsystem.main.FlightBookingSystemException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DeleteFlightWindow extends JFrame implements ActionListener {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MainWindow mw;
    private JTextField flightIdText = new JTextField();

    private JButton deleteBtn = new JButton("Delete");
    private JButton cancelBtn = new JButton("Cancel");

    /**
     * Constructs a new DeleteFlightWindow object with a reference to the main window.
     * @param mw The MainWindow object representing the main window of the application.
     */
    public DeleteFlightWindow(MainWindow mw) {
        this.mw = mw;
        initialize();
    }

    /**
     * Initializes the contents of the frame, setting up the layout and components.
     */
    private void initialize() {
        setTitle("Delete Flight");

        setSize(300, 150);
        JPanel topPanel = new JPanel();
        topPanel.setLayout(new GridLayout(2, 2));
        topPanel.add(new JLabel("Flight ID: "));
        topPanel.add(flightIdText);

        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new GridLayout(1, 3));
        bottomPanel.add(new JLabel("     "));
        bottomPanel.add(deleteBtn);
        bottomPanel.add(cancelBtn);

        deleteBtn.addActionListener(this);
        cancelBtn.addActionListener(this);

        this.getContentPane().add(topPanel, BorderLayout.CENTER);
        this.getContentPane().add(bottomPanel, BorderLayout.SOUTH);
        setLocationRelativeTo(mw);

        setVisible(true);
    }

    /**
     * Handles action events generated by buttons in the window.
     * @param ae The ActionEvent object representing the action event.
     */
    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource() == deleteBtn) {
            deleteFlight();
        } else if (ae.getSource() == cancelBtn) {
            this.setVisible(false);
        }
    }

    /**
     * Deletes the flight specified by the user input after confirmation.
     */
    private void deleteFlight() {
        try {
            int flightId = Integer.parseInt(flightIdText.getText());

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this flight?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Create and execute the DeleteFlight Command
                Command deleteFlight = new DeleteFlight(flightId);
                deleteFlight.execute(mw.getFlightBookingSystem());

                // Refresh the view with the list of flights
                mw.displayAllFlights();

                // Hide (close) the DeleteFlightWindow
                this.setVisible(false);
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Flight ID must be a valid integer", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (FlightBookingSystemException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
